repos:
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.10
    hooks:
      - id: actionlint-docker
        types: ["file", "non-executable", "text", "yaml"]
        files: ^.github/workflows