name: "Building i18n files"
description: "Building translation files for the i18n library"
author: text-adi
runs:
  using: node24
  main: dist/index.cjs
inputs:
  dir:
    description: 'Directory to search for .po files'
    required: false
    default: '.'
branding:
  icon: refresh-ccw
  color: green