name: Test

on:
  pull_request:
    types:
      - synchronize
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v6
      - run: |
          mkdir ./test
          mkdir ./test/main
          mkdir ./test/another

      - name: Create file
        env:
          PO_CONTENT: ${{ vars.TEMPLATE }}
        run: |
          echo "$PO_CONTENT" > "test/file.po"

      - name: Check create file
        run: |
          ls -la           
          tail ./test/file.po

      - name: Create new file for build
        run: |
          cp ./test/file.po ./test/main/file.po
          cp ./test/file.po ./test/another/file.po
          ls -la ./test

      - uses: ./
        with:
          dir: ./test/another

      - name: Check Test - 1
        run: |
          expected_files=("file.po" "file.mo")
          directory="./test/another"
          for file in "${expected_files[@]}"; do
            if [[ ! -f "$directory/$file" ]]; then
              echo "File $file not found in dir $directory/$file" && ls -la $directory && exit 1
            fi
          done

      - name: Check Test - 2
        run: |
          expected_files=("file.mo")
          directory="./test/main"
          for file in "${expected_files[@]}"; do
            if [[ -f "$directory/$file" ]]; then
              echo "File $file found in $directory/$file" && ls -la $directory && exit 1
            fi
          done

      - name: Install msgfmt (gettext)
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get update && sudo apt-get install -y gettext
          elif [ "$RUNNER_OS" == "Windows" ]; then
            choco install gettext -y
          elif [ "$RUNNER_OS" == "macOS" ]; then
            brew install gettext
            echo "$(brew --prefix gettext)/bin" >> "$GITHUB_PATH"
          fi

      - name: Verify msgfmt
        run: msgfmt --version